spring:
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
  datasource:
    url: jdbc:oracle:thin:@fei-sql3.upceucebny.cz:1521:BDAS
    username: st58617
    password: abcde
  liquibase:
    change-log:
      classpath: db/changelog/master.xml

server:
  port: 8090

# TODO: change vals
jwt:
  token:
    secret: secret
    expire: 3600000